### ISSUE TITLE
Missing TreePanel's lines when using 'lines=True' on Triton theme

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1586]
Found: 4.5.1
Ext.NET forum thread: [Tree Panel with lines](https://forums.ext.net/showthread.php?62364)
Sencha thread: [TreePanel: tree lines in Triton theme](https://www.sencha.com/forum/showthread.php?305738)

Enabling tree panel's sub-nodes lines has no effect in the Triton theme. This has been reported in Sencha a while ago and still not fixed.

This can be easily noticed in the [Basic TreePanel example](http://examples.ext.net/#/Kitchen_Sink/TreePanels/Basic_TreePanel/). Only reproducible for the Triton theme.

**Comment by fabriciomurta** [comment]
These two CSS may be used to get (to some extent) the functionality:
```css
        .x-tree-lines .x-tree-elbow-line {
            background-image: url(/extjs/packages/theme_triton/build/resources/images/tree/elbow-line-png/ext.axd);
        }

        .x-tree-lines .x-tree-elbow {
            background-image: url(/extjs/packages/theme_triton/build/resources/images/tree/elbow-png/ext.axd);
        }
```
as the images are present in the triton theme itself. But the row height does not match it and the result is not suitable as a solution without further adjusts. It might be better to enable glyphs from font awesome instead.

**Comment by fabriciomurta** [comment]
This CSS style block seems to be suitable as an workaround (although the 'end' lines are not centered to the icon):

```css
.x-tree-lines .x-tree-elbow {
    background-image: url(/extjs/packages/theme_triton/build/resources/images/tree/elbow-png/ext.axd);
    background-repeat-y: repeat;
}

.x-tree-lines .x-tree-elbow-line {
    background-image: url(/extjs/packages/theme_triton/build/resources/images/tree/elbow-line-png/ext.axd);
    background-repeat-y: repeat;
}

.x-tree-lines .x-tree-elbow-end {
    background-image: url(/extjs/packages/theme_triton/build/resources/images/tree/elbow-end-png/ext.axd);
    margin-top: -11px;
}
```
