### ISSUE TITLE
Option to toggle grid column headers' text wrapping

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1682]
Found: 5.0.0
Ext.NET forum thread: [wrap column header text](https://forums.ext.net/showthread.php?62746)

It is not trivial to allow text wrapping in grid column headers. Currently one way to do this, is to override the following CSS rule:

```css
.x-column-header-inner, .x-column-header-inner span { white-space:normal; }
```

So, the text wrapping is set at theme-level. There should be a setting, component-level, to allow this configuration across all themes.

Basically, a config option adding the CSS rule (programmatically) to the specific columns that should allow text wrapping would work best. So a setting in the column definition that'd be referenced during header draw procedure.
